/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projects;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    // @Test void appHasAGreeting() {
    //     Connect4 classUnderTest = new Connect4();
    //     assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    // }
}
